import { inter } from "./fonts";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-dvh from-[#010018] to-[#262449] bg-gradient-to-b`}>{children}</body>
    </html>
  );
}
